# Generated by Django 6.0.3 on 2026-03-22 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('city_area', models.CharField(max_length=100)),
                ('property_type', models.CharField(choices=[('3BHK', '3 BHK'), ('2BHK', '2 BHK'), ('1BHK', '1 BHK'), ('1RK', '1 RK'), ('SR', 'Single Room')], max_length=10)),
                ('listing_type', models.CharField(choices=[('rent', 'for Rent'), ('sale', 'for sale')], default='rent', max_length=10)),
                ('price', models.IntegerField(help_text='Monthly rent or Sale Price in rs')),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='properties/')),
                ('media_type', models.CharField(choices=[('image', 'image'), ('video', 'video')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='properties.property')),
            ],
        ),
    ]
