# Generated by Django 6.0 on 2025-12-23 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='area',
            new_name='city_area',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='descriptions',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='property',
            name='city',
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('3BHK', '3 BHK'), ('2BHK', '2 BHK'), ('1BHK', '1 BHK'), ('1RK', '1 RK'), ('SR', 'Single Room')], default='3BHK', max_length=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PropertyMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='properties/media/')),
                ('media_type', models.CharField(choices=[('image', 'image'), ('video', 'video')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='properties.property')),
            ],
        ),
    ]
