# Generated by Django 6.0.3 on 2026-03-27 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyRequestMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='property_requests/')),
                ('media_type', models.CharField(choices=[('image', 'Image')], default='image', max_length=10)),
                ('property_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='properties.propertyrequest')),
            ],
        ),
    ]
