# Generated by Django 6.0.3 on 2026-04-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_propertyrequestmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='built_up_area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='carpet_area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='plot_area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('3BHK', '3 BHK'), ('2BHK', '2 BHK'), ('1BHK', '1 BHK'), ('1RK', '1 RK'), ('SR', 'Single Room'), ('RH', 'Row House'), ('BG', 'Bungalow'), ('PL', 'Plot')], max_length=10),
        ),
    ]
