"""
Django settings for shivtej_V_0 project.
Generated by 'django-admin startproject'
"""

import os
from pathlib import Path
import dj_database_url

# ------------------------------------------------
# Paths
# ------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent
print("BASE_DIR =", BASE_DIR)
# ------------------------------------------------
# Security
# ------------------------------------------------
SECRET_KEY = "django-insecure--ri1#r)a!$g^9+jk%o3nbz2r@#zahq7@m3zf_qawa+_l2rme=x"

# DEBUG = False

# for testing
DEBUG = True

ALLOWED_HOSTS = ["*", ".railway.app"]

CSRF_TRUSTED_ORIGINS = [
    "https://*.railway.app",
]

# ------------------------------------------------
# Installed Apps
# ------------------------------------------------
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "properties",
    "accounts",
    "core",
]

# ------------------------------------------------
# Middleware
# ------------------------------------------------
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",

    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",

    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",

    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# ------------------------------------------------
# URLs / WSGI
# ------------------------------------------------
ROOT_URLCONF = "shivtej_V_0.urls"

WSGI_APPLICATION = "shivtej_V_0.wsgi.application"

# ------------------------------------------------
# Templates
# ------------------------------------------------
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# ------------------------------------------------
# Database (Railway compatible)
# ------------------------------------------------

# DATABASES = {
#     "default": dj_database_url.config(
#         conn_max_age=600,
#         ssl_require=True
#     )
# }
#local database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'mydb',
        'USER': 'postgres',        # your postgres username
        'PASSWORD': 'root',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}
# ------------------------------------------------
# Password validation
# ------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# ------------------------------------------------
# Internationalization
# ------------------------------------------------
LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True
USE_TZ = True

# ------------------------------------------------
# Static files procution
# ------------------------------------------------
# STATIC_URL = "/static/"

# STATICFILES_DIRS = [
#     BASE_DIR / "static",
# ]

# STATIC_ROOT = BASE_DIR / "staticfiles"

# STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
# Static files (DEV)
STATIC_URL = "/static/"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]
STATIC_ROOT = BASE_DIR / "staticfiles"

# ❌ REMOVE these for now
# STATIC_ROOT = BASE_DIR / "staticfiles"
# STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# ------------------------------------------------
# Media files
# ------------------------------------------------
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# ------------------------------------------------
# Login redirects
# ------------------------------------------------
LOGIN_REDIRECT_URL = "/properties"
LOGOUT_REDIRECT_URL = "/"

# ------------------------------------------------
# Default PK
# ------------------------------------------------
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ------------------------------------------------
# Email backend (console for development)
# ------------------------------------------------
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"